default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db

development:
  <<: *default
  database: shop_review_development

test:
  <<: *default
  database: shop_review_test

production:
  <<: *default
  database: shop_review_production
  username: work
  password: <%= ENV['WORK_DATABASE_PASSWORD'] %>
